# Generated by Django 4.0.4 on 2022-05-07 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название книги')),
                ('chapter', models.CharField(choices=[['Добавить жанр', 'Добавить жанр'], ['tzfant', 'Фантастика зарубежная'], ['tofant', 'Фантастика отечественная'], ['t2mv', 'Вторая мировая война']], default='Добавить жанр', max_length=64, verbose_name='Жанр')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
            ],
        ),
    ]
